Organizations:

  - &OrdererOrg
    Name: OrderingService
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/agri-network.com/msp
    
    Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    OrdererEndpoints:
            - orderer.agri-network.com:7050

  - &Supplier
    Name: SupplierMSP
    ID: SupplierMSP
    MSPDir: crypto-config/peerOrganizations/supplier.agri-network.com/msp
    Policies:
          Readers:
              Type: Signature
              Rule: "OR('SupplierMSP.admin', 'SupplierMSP.peer', 'SupplierMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('SupplierMSP.admin', 'SupplierMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('SupplierMSP.admin')" 
          Endorsement:
              Type: Signature
              Rule: "OR('SupplierMSP.peer')"     

    AnchorPeers:
      - Host: peer0.supplier.agri-network.com
        Port: 7051

  - &Producer
    Name: ProducerMSP
    ID: ProducerMSP
    MSPDir: crypto-config/peerOrganizations/producer.agri-network.com/msp
    Policies:
          Readers:
              Type: Signature
              Rule: "OR('ProducerMSP.admin', 'ProducerMSP.peer', 'ProducerMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('ProducerMSP.admin', 'ProducerMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('ProducerMSP.admin')" 
          Endorsement:
              Type: Signature
              Rule: "OR('ProducerMSP.peer')" 

    AnchorPeers:
      - Host: peer0.producer.agri-network.com
        Port: 7051

  - &Deliverer
    Name: DelivererMSP
    ID: DelivererMSP
    MSPDir: crypto-config/peerOrganizations/deliverer.agri-network.com/msp
    Policies:
          Readers:
              Type: Signature
              Rule: "OR('DelivererMSP.admin', 'DelivererMSP.peer', 'DelivererMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('DelivererMSP.admin', 'DelivererMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('DelivererMSP.admin')" 
          Endorsement:
              Type: Signature
              Rule: "OR('DelivererMSP.peer')" 

    AnchorPeers:
      - Host: peer0.deliverer.agri-network.com
        Port: 7051

  - &Retailer
    Name: RetailerMSP
    ID: RetailerMSP
    MSPDir: crypto-config/peerOrganizations/retailer.agri-network.com/msp
    Policies:
          Readers:
              Type: Signature
              Rule: "OR('RetailerMSP.admin', 'RetailerMSP.peer', 'RetailerMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('RetailerMSP.admin', 'RetailerMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('RetailerMSP.admin')" 
          Endorsement:
              Type: Signature
              Rule: "OR('RetailerMSP.peer')" 

    AnchorPeers:
      - Host: peer0.retailer.agri-network.com
        Port: 7051

Capabilities:

    Channel: &ChannelCapabilities

        V2_0: true


    Orderer: &OrdererCapabilities
    
        V2_0: true

    Application: &ApplicationCapabilities

        V2_0: true
# Orderer

Orderer: &OrdererDefaults

    OrdererType: solo
    Addresses: 
        - orderer.agri-network.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers: 
            - 127.0.0.1:9092

    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
Channel: &ChannelDefaults

    Policies:

        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"

        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"


    Capabilities:
        <<: *ChannelCapabilities
# Application

Application: &ApplicationDefaults

    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

Profiles:
    OrdererGenesis:
      <<: *ChannelDefaults
      Capabilities:
        <<: *ChannelCapabilities
      Orderer:
        <<: *OrdererDefaults
        Organizations:
          - *OrdererOrg
        Capabilities:
          <<: *OrdererCapabilities
      Consortiums:
        MyFirstConsortium:
          Organizations:
            - *Supplier 
            - *Producer
            - *Deliverer
            - *Retailer
            
    ChannelDemo:
      Consortium: MyFirstConsortium
      <<: *ChannelDefaults
      Application:
        <<: *ApplicationDefaults
        Organizations:
          - *Supplier 
          - *Producer
          - *Deliverer
          - *Retailer
          
        Capabilities:
          <<: *ApplicationCapabilities
