version: '2'

services:

  orderer.agri-network.com:
    container_name: orderer.agri-network.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/opt/gopath/fabric-samples/agri-network/channel-artifacts/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/opt/gopath/fabric-samples/agri-network/channel-artifacts/genesis.block
    - ../crypto-config/ordererOrganizations/agri-network.com/orderers/orderer.agri-network.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/agri-network.com/orderers/orderer.agri-network.com/tls:/var/hyperledger/orderer/tls
    - orderer.agri-network.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.supplier.agri-network.com:
    container_name: peer0.supplier.agri-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - GODEBUG=netdns=go
      - CORE_PEER_ID=peer0.supplier.agri-network.com
      - CORE_PEER_ADDRESS=peer0.supplier.agri-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.supplier.agri-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.supplier.agri-network.com:7051
      - CORE_PEER_LOCALMSPID=SupplierMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/supplier.agri-network.com/peers/peer0.supplier.agri-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/supplier.agri-network.com/peers/peer0.supplier.agri-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.supplier.agri-network.com:/var/hyperledger/production
    ports:
      - 7051:7051
  

  peer0.producer.agri-network.com:
    container_name: peer0.producer.agri-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - GODEBUG=netdns=go
      - CORE_PEER_ID=peer0.producer.agri-network.com
      - CORE_PEER_ADDRESS=peer0.producer.agri-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.producer.agri-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.producer.agri-network.com:7051
      - CORE_PEER_LOCALMSPID=ProducerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/producer.agri-network.com/peers/peer0.producer.agri-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/producer.agri-network.com/peers/peer0.producer.agri-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.producer.agri-network.com:/var/hyperledger/production
    ports:
      - 8051:7051

  peer0.deliverer.agri-network.com:
    container_name: peer0.deliverer.agri-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - GODEBUG=netdns=go
      - CORE_PEER_ID=peer0.deliverer.agri-network.com
      - CORE_PEER_ADDRESS=peer0.deliverer.agri-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.deliverer.agri-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.deliverer.agri-network.com:7051
      - CORE_PEER_LOCALMSPID=DelivererMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/deliverer.agri-network.com/peers/peer0.deliverer.agri-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/deliverer.agri-network.com/peers/peer0.deliverer.agri-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.deliverer.agri-network.com:/var/hyperledger/production
    ports:
      - 9051:7051

  peer0.retailer.agri-network.com:
    container_name: peer0.retailer.agri-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - GODEBUG=netdns=go
      - CORE_PEER_ID=peer0.retailer.agri-network.com
      - CORE_PEER_ADDRESS=peer0.retailer.agri-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.retailer.agri-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.retailer.agri-network.com:7051
      - CORE_PEER_LOCALMSPID=RetailerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/retailer.agri-network.com/peers/peer0.retailer.agri-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/retailer.agri-network.com/peers/peer0.retailer.agri-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.retailer.agri-network.com:/var/hyperledger/production
    ports:
      - 10051:7051
